<a href="https://colab.research.google.com/github/samandarustaperdiev/mohirdev_NumPy/blob/main/mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [2]:
arr = np.array([1, 2, 3, 4, 5])
arr.ndim

1

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [6]:
zero = np.zeros(9)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [11]:
arr1 = np.arange(8)
arr1.itemsize
np.size(arr1)

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [16]:
np.info('add')

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is creat

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [18]:
arr = np.zeros(12)
arr[6] = 1
print(arr)

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [19]:
arr = np.arange(20,59)
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [25]:
arr = -np.arange(-59,-20)
arr

array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43,
       42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,
       25, 24, 23, 22, 21])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [27]:
arr = np.arange(12,21).reshape(3, 3)
arr

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [29]:
arr = np.array([3, 7, 0, 0, 9, 0])
np.nonzero(arr)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [36]:
arr = np.random.rand(2, 2, 2)
arr

array([[[0.65501812, 0.72148926],
        [0.01129704, 0.06803294]],

       [[0.08980878, 0.37155802],
        [0.70025027, 0.48687144]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [56]:
arr = np.random.randn(9, 9)
print(arr)
print("kichik qiymat:", np.min(arr))
print("katta qiymat",np.max(arr))

[[-0.68695258  0.358518   -0.04533768 -0.73348265 -0.61684854  0.74070593
   0.11084397 -0.6425687  -1.35530202]
 [-1.92479662 -0.02730548 -0.3549702  -0.3826074   0.33047039  1.33652668
  -0.02062492  0.30703638 -0.96896342]
 [-0.29488769  0.52360016  0.19212004 -0.7806333  -0.34210456 -0.87429702
   0.45717007 -0.27675623  1.66653077]
 [ 0.13332631  0.40611629  0.60670514 -1.33003817  1.38859321  0.29395864
  -0.12491236 -0.34443332  0.48053365]
 [ 0.79229846 -0.20667567 -1.18573971  1.46543521  0.85416652 -0.53772667
  -1.61405026 -0.19868453  3.1556266 ]
 [ 0.03302636  0.01343281 -0.78788146 -1.4048629  -1.69883322 -0.43482979
   0.4440555  -0.40037075  1.07396673]
 [ 0.62762064 -2.06162719  0.17959255 -1.43296113 -1.61126069  0.15171816
  -0.49233887 -0.72248067  0.55662175]
 [ 0.67454786 -1.26160888  1.90359179  0.20615677 -0.65976667 -0.20346227
  -0.5424879   1.10780936 -1.52750459]
 [-0.02632113 -0.55686164 -0.54639657  1.00086068  0.97942119 -1.24670707
  -2.01304505 -0.98504

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [60]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [67]:
arr = np.arange(18).reshape(6, 3)
arr1 = np.arange(12).reshape(3, 4)
np.dot(arr, arr1)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218],
       [164, 203, 242, 281],
       [200, 248, 296, 344]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [68]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [73]:
a = np.array([1, 2])
b = np.array([4, 5])
print(a > b)
print(a >= b)
print(a < b)
print(a <= b)

[False False]
[False False]
[ True  True]
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [74]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-74-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-74-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [77]:
a = np.array([3,4,5, 6,9,2])
b = np.array([4, 5, 8])
np.intersect1d(a, b)

array([4, 5])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [83]:
arr = np.random.randn(5)
print(np.floor(arr))
print(arr.astype)
print(np.trunc(arr))

[ 0.  0.  0.  0. -2.]
<built-in method astype of numpy.ndarray object at 0x7ebb528ae790>
[ 0.  0.  0.  0. -1.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [99]:
arr = np.random.randint(3, size=(3,3))
arr

array([[1, 0, 2],
       [2, 2, 2],
       [2, 1, 2]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [105]:
arr = np.random.randn(10)
np.sort(arr)

array([-0.99047885, -0.55433418, -0.15534075, -0.10725742,  0.07099637,
        0.17647995,  0.5559457 ,  1.04863139,  1.74391134,  1.77860697])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [110]:
a = np.arange(8)
b = np.arange(8)
np.array_equal(a,b)

True

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [111]:
arr = np.arange(18).reshape(6,3)
arr1 = np.arange(12).reshape(3,4)
np.dot(arr, arr1)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218],
       [164, 203, 242, 281],
       [200, 248, 296, 344]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [126]:
arr = np.random.rand(5)
np.sort(arr)
arr[-1] = 0
arr

array([0.55063347, 0.88717501, 0.61620854, 0.29387041, 0.        ])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [151]:
data = np.datetime64(10, 'Y')
data


numpy.datetime64('1980')

#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [137]:
arr = np.random.randn(5)
print(arr)
print(np.floor(arr))
print(arr.astype)
print(np.trunc(arr))

[-1.42945326 -0.39825733 -1.67987052 -0.60945618 -1.54089349]
[-2. -1. -2. -1. -2.]
<built-in method astype of numpy.ndarray object at 0x7ebb528af3f0>
[-1. -0. -1. -0. -1.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [138]:
arr = np.arange(5)
np.add.reduce(arr)

10

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [140]:
arr = np.arange(1, 6)
arr

array([1, 2, 3, 4, 5])

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?




```
# Выбран кодовый формат
```

`💡Ishora` stride_tricks.as_strided

In [150]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [141]:
arr = np.array([3,3,3,2,2,6,6,8,8,])
np.bincount(arr)

array([0, 0, 2, 3, 0, 0, 2, 0, 2])

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`